# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageCourse', '0003_auto_20151221_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manageCourse.Teacher'),
        ),
    ]
